### ISSUE TITLE
Potential Improvments

### ISSUE THREAD

**Issue by 0xpatrickdev** [0xpatrickdev/agoric-vault-collateralization-notifier#1]
### Client

- [x] show gov params and current collateralization in addNotifier modal (see #4)
- [ ] logout button to disconnect email auth session
- [ ] disconnect button to disconnect wallet
- [ ] add network dropdown
- [ ] manual wallet address input

### Server

- [ ] send email notification when a new Notifier is created or deleted
- [ ] handle multiple networks/environments (currently, a server needs to be deployed for each environment)
- [ ] rate limiting, perhaps with something like @fastify/rate-limit

### Both

- [x] incorporate `decimals` from `displayInfo`. Current app assumes `6` for all denoms (see #2)
- [x] GitHub Workflow for CI/CD (see #3)
- [ ] use basis points (as in integer) instead of percents to store collateralizationRatios. Users can specify '250.55%' instead of just '250%'.
- [ ] ability to edit existing notifiers (versus deleting and recreating)

**Comment by 0xpatrickdev** [comment]
- [ ] incorporate `decimals` from `displayInfo`. Current app assumes `6` for all denoms
